### ISSUE TITLE
Record icon not updated on Records page during upload

### ISSUE THREAD

**Issue by ianholmes** [edina/fieldtrip-gb#153]
If you're on the Records page of the app and upload all the records to DropBox, the icon next to each record doesn't update to show if the record was successfully uploaded or not.  The only way to get the icon to update is to move off the Records page and then go back to it.  Note the name of the record is updated (e.g. if the record is renamed because it has the same name as an existing record).

This was on an iPhone 4s running iOS 8.1.1

**Comment by gmh04** [comment]
ok in ftgb 1.5
