### ISSUE TITLE
Migrate records in dropbox to new record format

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-gb#160]
This will probably be done from the authoring tool.  We need to identify if there are any records in dropbox that have been created by FTGB <= 1.3.  If there are they need to be converted to the new record format.

**Comment by benismobile** [comment]
additional requirement is to create some kind of archive for existing records using old format, before converting existing records.

**Comment by panterz** [comment]
I added function that updates any existing record with the old format and makes a backup of old record. I am not backing up any assets. It might make request to be slower. What do you think?
