### ISSUE TITLE
pcapi is dependant on the record format

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-gb#165]
Here's the workflow we decided to implement:

1. AT --> get records
2. if record in old format
3. back it up
4. convert it 
5. replace it

However, there's a functionality on the Authoring Tool where the record is fetched and the user can edit. The old pcapi knows about the old format and on the GET request of the record it goes and does a check against the assets because we had problems in the past where there were incomplete records. (problem with uploading a photo)

The problem above indicates that we need to implement functionality in the PCAPI where we need to cover the new format and release a new pcapi. I believe and I think many people agree that PCAPI should be simplified and be more transparent against the record format. Each validation or task that has to do with the record or the editor should take place on the client. PCAPI should be only a middleware. 

The question is if it is the time to have only one PCAPI that covers all the cases and be more transparent. That implies quite a bit of work but it has to happen at some point and is better sooner than later.

**Comment by gmh04** [comment]
I would sum up our discussion by saying take the latest pcapi core - wherever that is -  install it on rainbow and get it working for FTGB 1.4 and FTGB 1.5.

**Comment by panterz** [comment]
Beta server is updated with the latest pcapi. People can test it now.

**Comment by gmh04** [comment]
Looks good on ftgb 1.4 & 1.5
