### ISSUE TITLE
Error fetching records on authoring tool

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-gb#166]
To reproduce, ensure you have a mix of records created by FTGB 1.4 & 1.5

On dlib-rainbow Do Get Records.

On chrome error pop "DataTables warning (table id = 'example'): Requested unknown parameter 'editor' from the data source for row 0"

**Comment by gmh04** [comment]
related to https://github.com/edina/fieldtrip-gb/issues/160

**Comment by panterz** [comment]
Get records is working.

**Comment by gmh04** [comment]
I just repeated this test

1) On FTGB 1.4 I created 2 records synced.
2) Created a third record.
3) Upgraded to FTGB 1.5
4) Created two records.

Went to authoring tool and fetched records.  No error but only 3 records are displayed (the records created in steps 2 and 4).

**Comment by panterz** [comment]
There's no error and the records are on dropbox and are converted. If you refetch then you'll have 5 points.

**Comment by panterz** [comment]
The records are being converted, backedup and visualized properly on the map
