### ISSUE TITLE
409 error while fetching image that came from the gallery of the mobile

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-gb#168]
To reproduce it:
1. Capture a new record with image, use image from gallery
2. upload it (the image filename will be modified.jpg and the value inside the record.json will be modified.jpg?timestap
3. Login to AT, get records, edit the record, check your console logs

**Comment by benismobile** [comment]
this appears to be live issue still - see incident http://vorlichdb.edina.ac.uk:9999/ims/getincident/?id=479

**Comment by gmh04** [comment]
The records related to the above incident were generated by version 1.4.7
