### ISSUE TITLE
If the user has an incomplete record the app fails to initialize

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-gb#182]
If the user has an incomplete record, in this case without lon/lat the execution gets interrupted and it's fatal, the app is half-initialized, no map and some buttons missing

``` log
Convert to new record format records.js:447
{
  "1": {
    "record": {
      "name": "one",
      "editor": "one.edtr"
    }
  },
  "2": {
    "record": {
      "name": "two",
      "editor": "two.edtr"
    }
  },
  "3": {
    "record": {
      "name": "three",
      "editor": "two.edtr"
    }
  },
  "4": {
    "record": {
      "name": "four",
      "editor": "two.edtr"
    }
  }
} utils.js:702
Uncaught TypeError: Cannot read property 'lon' of undefined records.js:455
```

**Comment by rgamez** [comment]
The test that is creating that very old record format is updated but I leave it open because a simple wrong record should not affect the app initialization.

**Comment by gmh04** [comment]
I don't know how to reproduce this.  I can't see a scenario where users would have records with no location, so closing this issue.
