### ISSUE TITLE
issue with authoring tool rendering on firefox windows

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#185]
Windows 7
FF 31.1.1 (ESR channel) whatever that is

**Comment by gmh04** [comment]
Struggling to reproduce this.  Works on managed desktop with Firefox 32.0.2 (note: non ESR version).  If these desktops are managed why do they have different Firefox version?  Perhaps try upgrading?

**Comment by benismobile** [comment]
happy to close this
