### ISSUE TITLE
cannot upload custom form records

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#189]
I have a custom form "signs of spring". 
The records I created with this form to not upload properly record.json is created but no assets are uplaoded.

**Comment by gmh04** [comment]
Ben, can you attach the form to the issue.

**Comment by benismobile** [comment]
<form id="form1019" data-ajax="false" novalidate>

<div class="fieldcontain" id="fieldcontain-text-1">
<label for="form-text-1">Record name</label>
<input name="form-text-1" id="form-text-1" type="text" required="" placeholder="Placeholder" maxlength="30" value="Spring">
</div>

<div class="fieldcontain" id="fieldcontain-select-1">
<fieldset>
<legend>Springy Things</legend>
<select id="form-select-1" required="">
<option value=""></option>
<option value="Darling Buds of May">Darling Buds of May</option>
<option value="Birds on Wing">Birds on Wing</option>
<option value="Host of golden Daffodills">Host of golden Daffodills</option></select>
</fieldset>
</div>

<div class="fieldcontain" id="fieldcontain-image-1">
<div class="button-wrapper button-camera">
<input name="form-image-1" id="form-image-1" type="file" accept="image/png" capture="camera" class="camera">
<label for="form-image-1">Take Picture</label>
</div>
</div>

<div class="fieldcontain" id="fieldcontain-audio-1">
<div class="button-wrapper button-microphone">
<input name="form-audio-1" id="form-audio-1" type="file" accept="audio/*" capture="microphone" class="microphone">
<label for="form-audio-1">Record Audio</label>
</div>
</div>

<div id="signs_of_spring-buttons" class="fieldcontain ui-grid-a">
<div class="ui-block-a">
<input type="submit" name="record" id="1019_record" value="Save">
</div>
<div class="ui-block-b">
<input type="button" name="cancel" id="1019_cancel" value="Cancel">
</div>
</div>
</form>

**Comment by benismobile** [comment]
```
<form id="form1019" data-ajax="false" novalidate>

<div class="fieldcontain" id="fieldcontain-text-1">
<label for="form-text-1">Record name</label>
<input name="form-text-1" id="form-text-1" type="text" required="" placeholder="Placeholder" maxlength="30" value="Spring">
</div>

<div class="fieldcontain" id="fieldcontain-select-1">
<fieldset>
<legend>Springy Things</legend>
<select id="form-select-1" required="">
<option value=""></option>
<option value="Darling Buds of May">Darling Buds of May</option>
<option value="Birds on Wing">Birds on Wing</option>
<option value="Host of golden Daffodills">Host of golden Daffodills</option></select>
</fieldset>
</div>

<div class="fieldcontain" id="fieldcontain-image-1">
<div class="button-wrapper button-camera">
<input name="form-image-1" id="form-image-1" type="file" accept="image/png" capture="camera" class="camera">
<label for="form-image-1">Take Picture</label>
</div>
</div>

<div class="fieldcontain" id="fieldcontain-audio-1">
<div class="button-wrapper button-microphone">
<input name="form-audio-1" id="form-audio-1" type="file" accept="audio/*" capture="microphone" class="microphone">
<label for="form-audio-1">Record Audio</label>
</div>
</div>

<div id="signs_of_spring-buttons" class="fieldcontain ui-grid-a">
<div class="ui-block-a">
<input type="submit" name="record" id="1019_record" value="Save">
</div>
<div class="ui-block-b">
<input type="button" name="cancel" id="1019_cancel" value="Cancel">
</div>
</div>
</form>

```

**Comment by benismobile** [comment]
can now upload the custom records. But having issues viewing them on the authoring tool

**Comment by gmh04** [comment]
you mean the ones that failed to upload, or the ones that succeeded?

**Comment by benismobile** [comment]
including one that appear to have succeeded

**Comment by gmh04** [comment]
These problems are related to the new empty fields appearing in the records (although this requirement came COBWEB I can find no issue).  As it stands at the moment these fields have no val field (see https://github.com/edina/fieldtrip-open/wiki/Record-Format#field), e.g:

{
    "id": "fieldcontain-image-1",
    "label": "Image"
}

I made a few changes (see above) to get the upload working, but now the pcapi doesn't like it when the authoring tool fetches these records:

2015-03-27 09:56:42,746 - pcapi.PCAPIRest:180 - DEBUG - check /records/Spring (26-03-2015 13h29m35s)/record.json
2015-03-27 09:56:42,746 - pcapi.PCAPIRest:444 - ERROR - Exception: 'val'
Traceback (most recent call last):
  File "/home/geoadmin/.local/lib/python2.6/site-packages/pcapi/rest.py", line 380, in fs
    res = self.provider.search(path.replace("record.json", ""), field["val"])
KeyError: 'val'

Now is probably a good time to stop and define what is means to have a field that has no value and update the documentation, app, pacpi and AT accordingly.

Our options are:

1) No field (as above)
2) empty string
3) null
4) undefined

**Comment by panterz** [comment]
@xmichael , what's your view on this? Something that will be less painful for pcapi while exporting the data into a db.

**Comment by panterz** [comment]
1. By having no field that makes things complicated for exporting the data to CSV so no
2. empty string can be a possible answer so might confuse the user
3. null seems the most appropriate one since it's json compliant
4. undefined is not valid in json

**Comment by xmichael** [comment]
Currently COBWEB handles this during export to PostGIS which already checks for missing a "val" (commit xmichael/pcapi@75bde3a )

Having said, I would go for option 3 (null) but only if there is no other case of missing val. Otherwise we will have this fixed for image fields but what about all other possible future regressions for fields where val might be accidentally left out?

In other words, let's use null but also let's make sure that it is used for all fields.

**Comment by gmh04** [comment]
App now creates records will fields with val field null.  pcapi returns:

```
{"msg": "The record is incomplete!", "error": 1}
```

http://dlib-rainbow.edina.ac.uk/1.3/pcapi/records/dropbox/WhmdnHrrzHQoIv3X/none
