### ISSUE TITLE
FieldtripGB it's using local provider as default

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-gb#195]
Not sure if it's consequence of the migration to the new pcapi but if the endpoint is not changed to the test endpoint it tries to use the local provider 

```
Login with: /1.3/pcapi/auth/local pcapi.js:73
Poll: /1.3/pcapi/auth/local pcapi.js:83
```

**Comment by rgamez** [comment]
The real issue was in the template generation, a silent error when the index.json was extended, specifically the section3.title object was being extended by a string, this caused the whole section disappear from the index.html additionally in absence of login button (which sets the cloud-provider variable) trying to login from the records page defaults to the local provider.

**Comment by benismobile** [comment]
I'm having trouble logging into the version George sent out last week. Is
this the reason?

**Comment by rgamez** [comment]
In the FieldtripGB 1.5.0.3 version that George sent it is present the problem of login from the records page, if you login from the home page once the cloud-provider is set and the problem disappears.

**Comment by benismobile** [comment]
I'm having issue logging in from home page. Not sure what you mean by
setting provider.

**Comment by rgamez** [comment]
I've tested it against the live and the testing endpoints and it's working, did you try both?

**Comment by benismobile** [comment]
Yep my issue was unrelated.  I was having issue because using rainbow
outside firewall. Need to think how I can test this without rainbow.

**Comment by gmh04** [comment]
Perhaps install new pcapi on brook?

**Comment by benismobile** [comment]
Yep but brook is not an option in settings?

**Comment by gmh04** [comment]
Ben, after going to effort of adding brook to the app, deploying the pcapi etc it turns out that brook is also tied doing to our subnet.  So i've setup 'george 8000' as a proxy to rainbow.  Alternatively, you could set up a VPN on your device.

**Comment by benismobile** [comment]
Thanks George that's working for me. Haven't been able to do full testing
with authoring tool yet as currently full time child care duty but I'm on
the case;
