### ISSUE TITLE
after record migration editor filter not working

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#203]
after record migration the editor filter function on authoring tool does not seem to work.
searching without a filter was fine though and records seemed to be intact.

**Comment by benismobile** [comment]
note - the migration did not appear to happen until i searched for records (i.e. did not happen as part of login - is that expected?)

**Comment by gmh04** [comment]
As I understand it the records are converted during "Get Records".

I couldn't reproduce this.  I created 2 records with version 1.4.7 and uploaded them.  In the rainbow authoring tool I did "Get Records", then filtered by record name and it worked.  Tested on Firefox.

**Comment by benismobile** [comment]
So filter by editor type

**Comment by gmh04** [comment]
That works too.  This is the 'Search' text box you are using?

**Comment by gmh04** [comment]
I'll try a custom editor.

**Comment by gmh04** [comment]
Ok, we can reproduce it.

**Comment by panterz** [comment]
The prob is that filtering is working with the new record format. What needs to happen is a get records request to take place after the map is loaded. The request will convert all the old data and then the filtering will be working. @benismobile What do you think?

**Comment by benismobile** [comment]
so are we saying that if we do get records initially (pre-migration) without a filter and then try filtering (once records migrated) it will work ok?

**Comment by panterz** [comment]
yup, so we need to do that automatically when the user is logging in the authoring tool. The reason is that the filter functionality is looking for the editor inside the properties object which is the case for the new format but not for the old one. The simpler solution is the one I am suggesting.

**Comment by benismobile** [comment]
sounds reasonable. Actually, I'm not sure it's a bad idea in any case to start of with all the records being displayed. Do you think it is worth alerting the user to the fact that the records are being migrated?

**Comment by panterz** [comment]
I think we shouldn't alert him. It's an internal thing.

**Comment by panterz** [comment]
Can you try once more? Just deployed the change

**Comment by gmh04** [comment]
works for me

**Comment by benismobile** [comment]
I'm still seeing issue - testing on http://dlib-rainbow.edina.ac.uk/authoring

**Comment by gmh04** [comment]
Ben, can you show it to Panos.

**Comment by gmh04** [comment]
The pcapi/dropbox is being flooded with simultaneous requests - 2 * number of old records. This leads to the familiar pcapi error:

 2015-04-28 12:02:03,281 - pcapi.PCAPIRest:562 - ERROR - Exception: [503] u'Failed to grab locks for 866931596, please re-issue request.'
Traceback (most recent call last):
  File "/home/geoadmin/.local/lib/python2.6/site-packages/pcapi/rest.py", line 523, in fs
    md = self.provider.upload(path, fp, overwrite=True)
  File "/home/geoadmin/.local/lib/python2.6/site-packages/pcapi/dbox_provider.py", line 240, in upload
    metadata = self.__retry(e, upload_file)
  File "/home/geoadmin/.local/lib/python2.6/site-packages/pcapi/dbox_provider.py", line 133, in __retry
    raise httperror
ErrorResponse: [503] u'Failed to grab locks for 866931596, please re-issue request.'

The solution is to process the records synchronously.  This will take longer but will be more likely to succeed.  Any failures will be re-attempted up to 3 times.

**Comment by gmh04** [comment]
Ben, new version has been deployed.  Can you verify this?

**Comment by gmh04** [comment]
related
https://github.com/edina/fieldtrip-gb/issues/209
