### ISSUE TITLE
Automate releases of fieldtrip plugins

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-gb#204]
We need a way of automating releases on fieldtrip plugins.

**Comment by panterz** [comment]
The way it needs to work is through a command line. I've added a package.json in each plugin. The way to do it is:
npm install
npm run release patch/minor/major

and what it does is:
1. increment number on bower.json,package.json
2. git add -A
3. git commit -m 
4. git tag
5. git push files and tags

**Comment by panterz** [comment]
Here's the documentation as well:
https://github.com/edina/fieldtrip-open/wiki/Develop

**Comment by gmh04** [comment]
https://github.com/edina/fieldtrip-open/wiki/Develop#release-instructions
