### ISSUE TITLE
migration causing directory naming wierdness due to leading spaces

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#206]
I think this is when the "name" property in the legacy record has trailing spaces. Below is an example record.

```
{
  "editor": "Weather Details (1) (1).edtr",
  "fields": [
    {
      "id": "fieldcontain-text-2",
      "val": "12",
      "label": "Temprateure "
    },
    {
      "id": "fieldcontain-select-1",
      "label": "Wind Speed",
      "val": "Force 5 Fresh breeze 18-24 mph"
    },
    {
      "id": "fieldcontain-select-3",
      "label": "Wind Direction From",
      "val": "NW"
    },
    {
      "id": "fieldcontain-select-2",
      "label": "Cloud cover",
      "val": "2/8"
    },
    {
      "id": "fieldcontain-select-4",
      "label": "Visability ",
      "val": ">2km"
    },
    {
      "id": "fieldcontain-select-5",
      "label": "Precipitation",
      "val": "None"
    },
    {
      "id": "fieldcontain-text-6",
      "val": "Na",
      "label": "High Water"
    },
    {
      "id": "fieldcontain-text-7",
      "val": "na",
      "label": "Low Water"
    },
    {
      "id": "fieldcontain-textarea-2",
      "val": "bright sun shine",
      "label": "Notes"
    }
  ],
  "name": "                                                     (26-03-2015 13h57m59s)",
  "point": {
    "lon": -2.910164654075698,
    "lat": 53.494095442076265
  },
  "timestamp": "2015-03-26T14:00:09.587Z"
}
```

**Comment by benismobile** [comment]
I'm currently still seeing the issue of renaming directories after migration. Otherwise migration working - successfully migrated 73 records.

**Comment by panterz** [comment]
I've tried it with the record you've sent me which is not the same with the record that is on the big bunch of records you've sent me last week

**Comment by panterz** [comment]
Tested with the 73 records and is working. I'll do some more testing tomorrow.

**Comment by benismobile** [comment]
The records in backup folder should show records as they were previous to migration. But for buggy records where there was a leading space in the record name the backup record has been changed to remove the leading space. this should only be done for the new migrated record.

**Comment by panterz** [comment]
I've changed the order from
fix, backup, migrate
to
backup, fix, migrate

I've tested it with selective data and seems to be working.
Just a reminder: clean cache before you test.

**Comment by panterz** [comment]
Need to add this: check if records_backup is there and not do it again in the future

**Comment by gmh04** [comment]
Not sure if this is necessary, as surely it will only be there for us developers?  And if it does recopy it, is it such a big deal?

**Comment by benismobile** [comment]
it's our insurance policy. it means we have a way of recovering user state
pre-migration.
if for some reason we screw up and the migration causes a lot of problems
we can release a new script which use the snapshot.

**Comment by gmh04** [comment]
I know what the back up is for.  My point is, if records_backup is there and there is a second attempt at back up, then something has already screwed up.  Maybe I don't understand Panos comment, and will wait to speak to him on Fri.

**Comment by benismobile** [comment]
Sorry for stating obvious. I'll try again:
First the current backup process as i understand it is not clean - as
migration progresses the backup records are fixed - for example getting rid
of leading spaces -
the issue is what happens after first migration attempt. If users still use
the 1.4.7 client to upload old style records after migration the script
will run again in order to update these newly uploaded old style records.
Also if the first migrate attempt is aborted (user closes tab etc) and
restarted later unprocessed records will kick off the script again. So I
thought we may benefit a clean snapshot that never gets changed and only
happens once, capturing the state of the dropbox at the time of the first
and original migration attempt - before any migration processing has taken
place.

**Comment by gmh04** [comment]
Ok so perhaps I missed part of the discussion because the way the back up was working was a backup was made of the record (note only the record.json) at the same time as the record converted - one at a time.  Your comment above suggests that a backup of *all* records is made before migration.  This is good.  What happens however if the user aborts before the end of the backup.

**Comment by panterz** [comment]
So the ideal scenario would be the AT to fire up the pcapi to do the backup once and be also responsible each time the user downloads the records to fix the leading spaces. So in steps:
Once:
1. AT gets all records
2. sends a request to pcapi to backup the whole records folder
3. pcapi checks if that exists already, if not backs it up
4. AT is going through each record and converts the record

Each time:
1. AT get all records
2. check if the folder name is not in agreement with the name inside the record.json
3. updates the record.name on dropbox

Do we agree with all the steps above?

**Comment by benismobile** [comment]
So I tested this and the migration was successful. Only issue is that in the backup folder the folder name is still being renamed with leading spaces ( the name in the record is left as it was which is correct). So the problem arises if we want for some reason to re-run the migration. I should be able to delete the new records folder ( with migrated records in it) and rename the backup folder to records and then re-run the migration with the same results, But because the backup folder has some directories names with leading spaces these are no longer identified as being different to the record name ( the backup made the directory name and the record name the same - the both neow have leading spaces) so this time the directories with leading spaces are included in the new records folder.

**Comment by panterz** [comment]
I've updated pcapi and authoring tool to follow the new logic which is:
1. check if there are old records and back up the whole records folder (if the folder exists don't back it up again)
2. go through each record and check if there is leading space and fix it
3. if it is an old record format then convert it.

I tested it with the 77 records and is working fine.

**Comment by benismobile** [comment]
think I found an issue. To replicate start off migration then kill the browser tab half way through migration. re-open the authoring tool and resume migration. Script finds the records that still need to be migrated but does not seem to process them. spinning wheel of death.

**Comment by panterz** [comment]
Now it's not breaking. If the user interrupts the process and reloads the page then the app picks it up from where it left it.

**Comment by benismobile** [comment]
happy to say I've completed testing of this and all is satisfactory!
