### ISSUE TITLE
Custom forms creating prefix with leading whitespace

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#208]
I'm noticing a lot of records have 2 spaces before the default prefix record name. The directory name does not have leading spaces resulting in directory name and record name being different.

**Comment by benismobile** [comment]
so tested this in a bit more detail. It does not actually cause the migration to fail but leaves the records folder in an inconsistent state because the migration script creates a new folder (with 2 leading spaces) in the records directory with contains the new format record, but therefore does not replace the existing folder (with no leading spaces). This means that the old record is left in place and the migration script will run the conversion again and again as we never get rid of the legacy record.

**Comment by benismobile** [comment]
so it appears difficult to replicate this - perhaps the user in my dataset had habit of adding spaces to the prefix when creating his forms.

**Comment by panterz** [comment]
Cannot be replicated.
