### ISSUE TITLE
migration error with larger datasets?

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#209]
Problem converting the following record [503] u'Failed to grab locks for 866931596, please re-issue request.'

I've seen this a number of times running migration on my dataset - as far as I can tell does not have to do with individual records but can happen on any record in larger dataset.

**Comment by gmh04** [comment]
The migration should retry if this happens: see https://github.com/edina/fieldtrip-authoring-tool/blob/master/src/js/former/jquery.former.mapviewer.js#L519-L525

Although this is difficult to test, so there maybe a bug in there.

**Comment by benismobile** [comment]
perhaps we can put some extra debug code in to check if it is actually generating a new request. I can then try to replicate. Reassigning to Panos as he is likely updating this code anyway

**Comment by gmh04** [comment]
if you have a failure you should get the following message "Problem converting the following record: <name>".

In firebug console you should then see the new AJAX request.

**Comment by panterz** [comment]
So, I tried it and it worked for me with the data you've sent me.

**Comment by benismobile** [comment]
I did get the "problem converting following record" message.
I was suggesting we have debug output for the success callback and also right at the beigining of the method. that way we can see if the method is called a second (and third) time as it should be and whether the second post request returns or not.

**Comment by rgamez** [comment]
If this helps, Sandy had 89 records initially only 20 were converted and the conversion stopped with the '"Failed to grab locks" error and the spinner was on screen (I think this was before the latest changes), I reloaded the page and the 69 remained were converted, it seems to me that the conversion stops if a single record conversion fails, as the '"Failed to grab locks"  is a transient error shouldn't the conversion try to convert as many as possible?

**Comment by gmh04** [comment]
I've tested the error handling and made improvements.  The migration should handle "Failed to grab locks" and any network problems with 3 re-attempts.  After that it will just give up and say there was a problem converting.  There is some improved errors messages as well.

Panos has deployed a new version to rainbow to try.
