### ISSUE TITLE
date search filter not working post migration

### ISSUE THREAD

**Issue by benismobile** [edina/fieldtrip-gb#212]
when using date to filter record search I'm getting 0 results.

**Comment by benismobile** [comment]
So this does not appear to be a migration issue. The date filter does not seem to be working for this record set pre-migration either,

**Comment by gmh04** [comment]
For date filtering the pcapi was using dropbox metadata timestamp (last update) not the record timestamp.

**Comment by benismobile** [comment]
did we fix this? I'm still getting issue testing on rainbow

**Comment by gmh04** [comment]
authoring tool have been deployed pointing to dlib-terzis

**Comment by gmh04** [comment]
perhaps highlights the importance of https://github.com/edina/fieldtrip-gb/issues/194

**Comment by panterz** [comment]
Fixed as far as concerned to where it points

**Comment by gmh04** [comment]
Ben you can retry this.  Please bear in mind this: https://github.com/edina/fieldtrip-osm/issues/45 and something I just noticed, the time on the record is different to the time stamp in the record - by up to half a second.

**Comment by benismobile** [comment]
appears to be working now
