### ISSUE TITLE
Upate all ftopen dependencies

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-gb#225]

**Comment by gmh04** [comment]
Upgrading to cordova 5 was a step too far, non core plugins were failing due to change in the way plugins are added.  Even plugman didn't know about this change: https://issues.apache.org/jira/browse/CB-9198.  So had to settle with 4.3.1.

Don't upgrade your android sdk tools to 24.3.1, or during android build you'll get

```
/path/to/sdk/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/path/to/ftgb/platforms/android/com.google.playservices/mobile-google-play-services_lib/${aapt}" (in directory "/path/to/ftgb/platforms/android/com.google.playservices/mobile-google-play-services_lib"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
...
```

see
http://stackoverflow.com/questions/30805037/cordova-build-fails-cant-find-appt.  I downgraded sdk tool with http://dl.google.com/android/android-sdk_r24.2.0-linux.tgz.

**Comment by gmh04** [comment]
related: https://github.com/edina/fieldtrip-gb/issues/91

**Comment by rgamez** [comment]
in OSX 24.3.1 works fine but not 24.3.2

**Comment by gmh04** [comment]
yes, that was typo, cheers
