### ISSUE TITLE
Authoring Tool needs to have better error handling if records are incomplete

### ISSUE THREAD

**Issue by ianholmes** [edina/fieldtrip-gb#226]
If an audio file or photograph is not present in DropBox for a specific record when you press the 'view/edit record' button in the Authoring Tool you just get a message back saying 'The record is incomplete!'.  It would be much better if it said what was missing from it.

**Comment by gmh04** [comment]
see
https://github.com/edina/pcapi/blob/1.3/src/pcapi/rest.py#L503
