### ISSUE TITLE
Cannot move Position Push-pin 

### ISSUE THREAD

**Issue by PopeTech** [edina/fieldtrip-gb#94]
Cannot re-position location pushpin.  Android 4.1 / GPS off

**Comment by rgamez** [comment]
If you go to download map and hold the slider, a loupe will pop up, after that if you try to capture any record the paddle/push-pin is stuck, the only way that I found to restore the normal behaviour is terminate the app.

**Comment by rgamez** [comment]
Fixed here: https://github.com/edina/fieldtrip-offline-maps/commit/3003f659fd5ad9969f2271678fb26b925b9fe256
